import './global.css';
import Link from 'next/link';

export const metadata = {
  title: 'Welcome to table-together',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <ul>
            <li>
              <Link href="/tableList">Table List</Link>
            </li>
            <li>
              <Link href="/tableCreate">Table Create</Link>
            </li>
          </ul>
        </nav>
        <main>{children}</main>
      </body>
    </html>
  );
}
